In [2]:
pip install pyodbc mssql sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyodbc in c:\programdata\anaconda3\lib\site-packages (5.1.0)
Requirement already satisfied: mssql in c:\users\acer\appdata\roaming\python\python312\site-packages (1.0.1)
Requirement already satisfied: sqlalchemy in c:\programdata\anaconda3\lib\site-packages (2.0.34)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\acer\appdata\roaming\python\python312\site-packages (from sqlalchemy) (4.16.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import pandas as pd
from sqlalchemy import create_engine

In [6]:
server = 'DESKTOP-I788VCF'
database = 'BikeStores'

connection_url = f"mssql+pyodbc://@{server}/{database}?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes"
engine = create_engine(connection_url)

In [9]:
query = '''
    select 
    sc.customer_id, sc.first_name, sc.last_name, sc.email, sc.street, so.order_status, so.order_date
    from sales.customers sc
    join sales.orders so
    on sc.customer_id = so.customer_id
    where sc.state= 'TX' and so.order_status=3;
'''
query_df =pd.read_sql(query,engine)

In [10]:
query_df

,customer_id,first_name,last_name,email,street,order_status,order_date
0,13,Lashawn,Ortiz,lashawn.ortiz@msn.com,27 Washington Rd.,3,2016-05-27
1,14,Garry,Espinoza,garry.espinoza@hotmail.com,7858 Rockaway Court,3,2016-08-05
2,20,Aleta,Shepard,aleta.shepard@aol.com,684 Howard St.,3,2017-02-27
3,21,Tobie,Little,tobie.little@gmail.com,10 Silver Spear Dr.,3,2017-10-12
4,43,Mozelle,Carter,mozelle.carter@aol.com,895 Chestnut Ave.,3,2017-06-10
5,50,Cleotilde,Booth,cleotilde.booth@gmail.com,17 Corona St.,3,2016-02-11
6,56,Lolita,Mosley,lolita.mosley@hotmail.com,376 S. High Ridge St.,3,2017-03-15
7,61,Elinore,Aguilar,elinore.aguilar@msn.com,9766 Rockcrest Ave.,3,2016-08-23
8,64,Bobbie,Foster,bobbie.foster@yahoo.com,988 Pineknoll Ave.,3,2016-11-12
9,66,Lorrie,Becker,lorrie.becker@yahoo.com,19 North Court,3,2017-05-13
10,68,Jayne,Kirkland,jayne.kirkland@hotmail.com,7800 Second Lane,3,2017-06-02
11,77,Keri,Bridges,keri.bridges@gmail.com,8504 Brickell Ave.,3,2016-09-01
12,116,Merlene,Vinson,merlene.vinson@gmail.com,431 Vine Dr.,3,2017-08-08
13,117,Dacia,William,dacia.william@msn.com,62 Cypress Drive,3,2016-04-04
14,119,Thalia,Dillard,thalia.dillard@yahoo.com,987 NE. Gates Street,3,2018-07-10
15,123,Robena,Hill,robena.hill@hotmail.com,263 Cross St.,3,2018-07-01
16,135,Dorthey,Jackson,dorthey.jackson@msn.com,9768 Brookside St.,3,2018-11-28
17,136,Sarita,Parks,sarita.parks@msn.com,7809 Second Lane,3,2018-12-28
18,153,Laraine,Robbins,laraine.robbins@yahoo.com,8214 E. Pin Oak Lane,3,2017-04-01

In [12]:
query_sp = '''
    declare @OutputMessage Varchar(100)
    exec usp_checkOrderStatus @OrderID = 1, @ResponseMessage = @OutputMessage Output
    select @OutputMessage as Order_Status_Message
'''
query_sp_df = pd.read_sql(query_sp, engine)
query_sp_df

                                Order_Status_Message
0  Order ID: 1 has been delivered to its destinat...